syntax = "proto3";

option go_package = "github.com/AusterDev/nybl/pkg/proto/gen/auth";

message AccountCreateRequest {
    string email = 1;
    string name = 2;
    string acc_pin = 3;
    map<string, Device> devices = 4;
}

message AccountCreateResponse {
    string id = 1;
    string name = 2;
    string email = 3;
}

message AcccountAuthenRequest {
    string email = 1;
    string deviceID = 2;
    string acc_pin = 3;
}

message AccountAuthenResponse {
    string account = 1;
}

message Device {
    string id = 1;
    string name = 2;
    string public_key = 3;
}

service AuthService {
    rpc CreateAccount(AccountCreateRequest) returns (AccountCreateResponse);
    rpc GetAccount(AcccountAuthenRequest) returns (AccountAuthenResponse);
}